/**
 * Format audit report as Markdown — ready to paste into a GitHub issue.
 */
export function formatMarkdown(report) {
  const lines = [];

  lines.push(`## RTL Audit Report — ${report.projectName}`);
  lines.push('');
  lines.push(`*Generated by [rtl-first](https://github.com/imohad/rtl-first) v${report.version}*`);
  lines.push('');
  lines.push(`**RTL Readiness Score: ${report.score.total}/100 (${report.score.grade})**`);
  lines.push('');

  // Summary table
  lines.push('| Layer | Status | Summary |');
  lines.push('|-------|--------|---------|');

  const layers = [
    { key: 'layer1', name: 'Text engine', data: report.layers.layer1 },
    { key: 'layer2', name: 'Direction logic', data: report.layers.layer2 },
    { key: 'layer3', name: 'CSS layout', data: report.layers.layer3 },
    { key: 'layer4', name: 'Translations', data: report.layers.layer4 },
    { key: 'layer5', name: 'Hardcoded text', data: report.layers.layer5 },
  ];

  for (const { name, data } of layers) {
    const icon = data.status === 'pass' ? '✅' : data.status === 'warn' ? '⚠️' : '❌';
    lines.push(`| ${name} | ${icon} | ${data.summary} |`);
  }

  lines.push('');

  // Details per layer
  for (const { key, name, data } of layers) {
    if (data.status === 'pass') continue;

    lines.push(`### ${name}`);
    lines.push('');
    lines.push(data.detail);
    lines.push('');

    if (key === 'layer3' && data.breakdown) {
      const entries = Object.entries(data.breakdown).slice(0, 8);
      if (entries.length > 0) {
        lines.push('| Property | Occurrences |');
        lines.push('|----------|------------|');
        for (const [prop, count] of entries) {
          lines.push(`| \`${prop}\` | ${count} |`);
        }
        lines.push('');
      }
    }

    if (key === 'layer4' && data.gaps) {
      for (const gap of data.gaps.slice(0, 3)) {
        if (gap.targetPath) {
          lines.push(`- \`en.json\`: ${gap.sourceKeyCount} keys`);
          lines.push(`- \`ar.json\`: ${gap.targetKeyCount} keys (${gap.missingKeys} missing)`);
        } else {
          lines.push(`- \`en.json\`: ${gap.sourceKeyCount} keys`);
          lines.push(`- \`ar.json\`: **not found**`);
        }
      }
      lines.push('');
    }

    if (key === 'layer5' && data.findings) {
      lines.push('<details>');
      lines.push(`<summary>Hardcoded strings (${data.count} found)</summary>`);
      lines.push('');
      for (const f of data.findings.slice(0, 20)) {
        lines.push(`- \`${f.file}:${f.line}\` — "${f.text}"`);
      }
      if (data.count > 20) {
        lines.push(`- ... and ${data.count - 20} more`);
      }
      lines.push('');
      lines.push('</details>');
      lines.push('');
    }

    if (data.fix) {
      lines.push(`**Fix:** \`${data.fix}\``);
      lines.push('');
    }
  }

  // Priority
  if (report.priority.length > 0) {
    lines.push('### Recommended priority');
    lines.push('');
    for (let i = 0; i < report.priority.length; i++) {
      lines.push(`${i + 1}. ${report.priority[i]}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Methodology: [The Five Layers of RTL Readiness](https://github.com/imohad/rtl-first/blob/main/docs/for-contributors/methodology.md)*');

  return lines.join('\n');
}
