/**
 * Format audit report for terminal output with colors and box drawing.
 */
export function formatTerminal(report) {
  const lines = [];
  const W = 56;

  const dim = (s) => `\x1b[2m${s}\x1b[0m`;
  const bold = (s) => `\x1b[1m${s}\x1b[0m`;
  const red = (s) => `\x1b[31m${s}\x1b[0m`;
  const yellow = (s) => `\x1b[33m${s}\x1b[0m`;
  const green = (s) => `\x1b[32m${s}\x1b[0m`;
  const cyan = (s) => `\x1b[36m${s}\x1b[0m`;

  const statusIcon = (status) => {
    if (status === 'pass') return green('✅');
    if (status === 'warn') return yellow('⚠️ ');
    return red('❌');
  };

  const statusLabel = (status) => {
    if (status === 'pass') return green('PASS');
    if (status === 'warn') return yellow('WARN');
    return red('FAIL');
  };

  // Header
  lines.push('');
  lines.push(bold(`  RTL Audit Report — ${report.projectName}`));
  lines.push(dim(`  Generated by rtl-first v${report.version}`));
  lines.push(dim('  ═'.repeat(28)));
  lines.push('');

  // Layer 1
  const l1 = report.layers.layer1;
  lines.push(`  ${statusIcon(l1.status)} ${bold('Layer 1 — Text engine')}        ${statusLabel(l1.status)}`);
  lines.push(`     ${l1.summary}`);
  if (l1.engines && l1.engines.length > 0) {
    for (const e of l1.engines) {
      lines.push(dim(`     → ${e.name}: ${e.bidiNote}`));
    }
  }
  lines.push('');

  // Layer 2
  const l2 = report.layers.layer2;
  lines.push(`  ${statusIcon(l2.status)} ${bold('Layer 2 — Direction logic')}    ${statusLabel(l2.status)}`);
  lines.push(`     ${l2.summary}`);
  if (l2.fix) lines.push(dim(`     → ${l2.fix}`));
  if (l2.uiLibraries && l2.uiLibraries.length > 0) {
    lines.push(dim(`     UI libraries: ${l2.uiLibraries.join(', ')}`));
  }
  lines.push('');

  // Layer 3
  const l3 = report.layers.layer3;
  lines.push(`  ${statusIcon(l3.status)} ${bold('Layer 3 — CSS layout')}         ${statusLabel(l3.status)}`);
  lines.push(`     ${l3.summary}`);
  if (l3.breakdown && Object.keys(l3.breakdown).length > 0) {
    const top5 = Object.entries(l3.breakdown).slice(0, 5);
    for (const [prop, count] of top5) {
      lines.push(dim(`     ${prop}: ${count} occurrences`));
    }
  }
  if (l3.fix) lines.push(dim(`     → Fix: ${l3.fix}`));
  lines.push('');

  // Layer 4
  const l4 = report.layers.layer4;
  lines.push(`  ${statusIcon(l4.status)} ${bold('Layer 4 — Translations')}       ${statusLabel(l4.status)}`);
  lines.push(`     ${l4.summary}`);
  if (l4.gaps && l4.gaps.length > 0) {
    for (const gap of l4.gaps.slice(0, 3)) {
      if (gap.targetPath) {
        lines.push(dim(`     en: ${gap.sourceKeyCount} keys → ar: ${gap.targetKeyCount} keys (${gap.missingKeys} missing)`));
      } else {
        lines.push(dim(`     en: ${gap.sourceKeyCount} keys → ar.json: not found`));
      }
    }
  }
  if (l4.fix) lines.push(dim(`     → Fix: ${l4.fix}`));
  lines.push('');

  // Layer 5
  const l5 = report.layers.layer5;
  lines.push(`  ${statusIcon(l5.status)} ${bold('Layer 5 — Hardcoded text')}     ${statusLabel(l5.status)}`);
  lines.push(`     ${l5.summary}`);
  if (l5.findings && l5.findings.length > 0) {
    for (const f of l5.findings.slice(0, 5)) {
      lines.push(dim(`     ${f.file}:${f.line} → "${f.text}"`));
    }
    if (l5.count > 5) {
      lines.push(dim(`     ... and ${l5.count - 5} more`));
    }
  }
  lines.push('');

  // Score
  lines.push(dim('  ─'.repeat(28)));
  lines.push('');

  const grade = report.score.grade;
  const gradeColor = grade === 'A' ? green : grade === 'B' ? green : grade === 'C' ? yellow : red;
  lines.push(`  ${bold('RTL Readiness Score:')} ${gradeColor(bold(`${report.score.total}/100`))} ${gradeColor(`(${grade})`)}`);
  lines.push('');

  // Score breakdown
  lines.push(dim(`     Layer 1: ${report.score.breakdown.layer1}/30  Layer 2: ${report.score.breakdown.layer2}/25  Layer 3: ${Math.round(report.score.breakdown.layer3)}/20`));
  lines.push(dim(`     Layer 4: ${Math.round(report.score.breakdown.layer4)}/15  Layer 5: ${Math.round(report.score.breakdown.layer5)}/10`));
  lines.push('');

  // Priority
  if (report.priority.length > 0) {
    lines.push(`  ${bold('Priority order:')}`);
    for (let i = 0; i < report.priority.length; i++) {
      lines.push(cyan(`     ${i + 1}. ${report.priority[i]}`));
    }
    lines.push('');
    lines.push(dim('  Tip: Open an issue before submitting any PR.'));
    lines.push(dim('  Guide: https://github.com/imohad/rtl-first'));
  }

  lines.push('');

  return lines.join('\n');
}
