/**
 * Patch Generators
 * Generates patch content for each RTL layer.
 * Patches are stored as shell scripts + diff files for maximum portability.
 * Zero dependencies.
 */

const fs = require('fs');
const path = require('path');

/**
 * Generate Layer 2 patch: Direction injection
 * Creates a script that adds dir="rtl" to the root element
 */
function generateDirectionPatch(dir, scanResult, lang = 'ar') {
  const lines = [];
  lines.push('#!/bin/bash');
  lines.push('# RTL Patch — Layer 2: Direction');
  lines.push(`# Generated by @rtl-first/patch-generator on ${new Date().toISOString().split('T')[0]}`);
  lines.push('# Adds dir="rtl" and lang attribute to root HTML element');
  lines.push('');
  lines.push('set -e');
  lines.push('');

  // Find root files to patch
  const rootFiles = [
    'app/layout.tsx', 'app/layout.jsx', 'src/app/layout.tsx', 'src/app/layout.jsx',
    'pages/_document.tsx', 'pages/_document.jsx', 'src/pages/_document.tsx',
    'app/root.tsx', 'app/root.jsx',
    'index.html', 'public/index.html', 'src/index.html', 'src/app.html'
  ];

  const foundFiles = rootFiles.filter(f => fs.existsSync(path.join(dir, f)));

  if (foundFiles.length === 0) {
    lines.push('echo "⚠ No root HTML file found — manual injection needed"');
    lines.push('exit 1');
  } else {
    for (const f of foundFiles) {
      const fullPath = path.join(dir, f);
      const content = fs.readFileSync(fullPath, 'utf8');

      if (/dir\s*=\s*["']rtl["']/.test(content)) {
        lines.push(`echo "✓ ${f} — dir=\\"rtl\\" already present"`);
        continue;
      }

      // Generate sed command based on file type
      if (f.endsWith('.html')) {
        lines.push(`# Inject into ${f}`);
        lines.push(`if grep -q 'dir="rtl"' "${f}" 2>/dev/null; then`);
        lines.push(`  echo "✓ ${f} — already has dir=\\"rtl\\""`);
        lines.push('else');
        lines.push(`  sed -i 's/<html/<html dir="rtl" lang="${lang}"/' "${f}"`);
        lines.push(`  echo "✓ ${f} — injected dir=\\"rtl\\" lang=\\"${lang}\\""`);
        lines.push('fi');
      } else {
        // JSX files: <html> or <Html>
        lines.push(`# Inject into ${f}`);
        lines.push(`if grep -q 'dir="rtl"' "${f}" 2>/dev/null; then`);
        lines.push(`  echo "✓ ${f} — already has dir=\\"rtl\\""`);
        lines.push('else');
        lines.push(`  sed -i 's/<html/<html dir="rtl" lang="${lang}"/' "${f}"`);
        lines.push(`  sed -i 's/<Html/<Html dir="rtl" lang="${lang}"/' "${f}"`);
        lines.push(`  echo "✓ ${f} — injected dir=\\"rtl\\" lang=\\"${lang}\\""`);
        lines.push('fi');
      }
      lines.push('');
    }
  }

  return {
    name: '01-direction.sh',
    layer: 2,
    description: 'Add dir="rtl" and lang attribute to root HTML element',
    content: lines.join('\n'),
    filesAffected: foundFiles.length
  };
}

/**
 * Generate Layer 3 patch: CSS logical properties
 * Creates a codemod script
 */
function generateCSSPatch(dir, scanResult) {
  const lines = [];
  lines.push('#!/bin/bash');
  lines.push('# RTL Patch — Layer 3: CSS Logical Properties');
  lines.push(`# Generated by @rtl-first/patch-generator on ${new Date().toISOString().split('T')[0]}`);
  lines.push(`# Converts physical CSS properties to logical equivalents`);
  lines.push(`# Files to process: ${scanResult.totalFiles}, Occurrences: ${scanResult.totalOccurrences}`);
  lines.push('');
  lines.push('set -e');
  lines.push('');

  if (scanResult.totalFiles === 0) {
    lines.push('echo "✓ No physical CSS properties found — nothing to patch"');
    return {
      name: '02-css-logical.sh',
      layer: 3,
      description: 'Convert CSS physical → logical properties',
      content: lines.join('\n'),
      filesAffected: 0
    };
  }

  // Generate the codemod inline
  lines.push('echo "Converting physical CSS properties to logical..."');
  lines.push('echo ""');
  lines.push('');
  lines.push('TOTAL=0');
  lines.push('');

  // Kebab-case replacements
  const replacements = [
    ['margin-left', 'margin-inline-start'],
    ['margin-right', 'margin-inline-end'],
    ['padding-left', 'padding-inline-start'],
    ['padding-right', 'padding-inline-end'],
    ['border-left-width', 'border-inline-start-width'],
    ['border-right-width', 'border-inline-end-width'],
    ['border-left-style', 'border-inline-start-style'],
    ['border-right-style', 'border-inline-end-style'],
    ['border-left-color', 'border-inline-start-color'],
    ['border-right-color', 'border-inline-end-color'],
    ['border-left', 'border-inline-start'],
    ['border-right', 'border-inline-end'],
    ['text-align: left', 'text-align: start'],
    ['text-align: right', 'text-align: end'],
  ];

  // camelCase replacements
  const camelReplacements = [
    ['marginLeft', 'marginInlineStart'],
    ['marginRight', 'marginInlineEnd'],
    ['paddingLeft', 'paddingInlineStart'],
    ['paddingRight', 'paddingInlineEnd'],
    ['borderLeft', 'borderInlineStart'],
    ['borderRight', 'borderInlineEnd'],
  ];

  // Build file list from scan
  lines.push('# File list from scan');
  lines.push('FILES=(');
  // Limit to top 200 files
  const filesToPatch = scanResult.fileList.slice(0, 200);
  for (const f of filesToPatch) {
    lines.push(`  "${f.path}"`);
  }
  lines.push(')');
  lines.push('');

  lines.push('for FILE in "${FILES[@]}"; do');
  lines.push('  if [ ! -f "$FILE" ]; then');
  lines.push('    echo "⚠ Skipped (not found): $FILE"');
  lines.push('    continue');
  lines.push('  fi');
  lines.push('');
  lines.push('  COUNT=0');

  // Apply kebab-case replacements
  for (const [from, to] of replacements) {
    const escaped = from.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    // Use word boundary-safe patterns
    if (from.includes(': ')) {
      lines.push(`  C=$(grep -c '${escaped}' "$FILE" 2>/dev/null || true)`);
      lines.push(`  if [ "$C" -gt 0 ]; then`);
      lines.push(`    sed -i 's/${escaped}/${to}/g' "$FILE"`);
      lines.push(`    COUNT=$((COUNT + C))`);
      lines.push('  fi');
    } else {
      // Property names: match with \b or followed by : or \s
      lines.push(`  C=$(grep -cE '${escaped}\\s*:' "$FILE" 2>/dev/null || true)`);
      lines.push(`  if [ "$C" -gt 0 ]; then`);
      lines.push(`    sed -i -E 's/${escaped}(\\s*:)/${to}\\1/g' "$FILE"`);
      lines.push(`    COUNT=$((COUNT + C))`);
      lines.push('  fi');
    }
  }

  // Apply camelCase replacements
  for (const [from, to] of camelReplacements) {
    lines.push(`  C=$(grep -c '${from}' "$FILE" 2>/dev/null || true)`);
    lines.push(`  if [ "$C" -gt 0 ]; then`);
    lines.push(`    sed -i 's/${from}/${to}/g' "$FILE"`);
    lines.push(`    COUNT=$((COUNT + C))`);
    lines.push('  fi');
  }

  lines.push('');
  lines.push('  if [ "$COUNT" -gt 0 ]; then');
  lines.push('    echo "  ✓ $FILE ($COUNT replacements)"');
  lines.push('    TOTAL=$((TOTAL + COUNT))');
  lines.push('  fi');
  lines.push('done');
  lines.push('');
  lines.push('echo ""');
  lines.push('echo "CSS codemod complete: $TOTAL total replacements"');

  return {
    name: '02-css-logical.sh',
    layer: 3,
    description: `Convert CSS physical → logical properties (${scanResult.totalFiles} files, ${scanResult.totalOccurrences} occurrences)`,
    content: lines.join('\n'),
    filesAffected: scanResult.totalFiles
  };
}

/**
 * Generate Layer 4 patch: Locale scaffolding
 * Creates a script that sets up ar.json
 */
function generateLocalePatch(dir, scanResult, lang = 'ar') {
  const lines = [];
  lines.push('#!/bin/bash');
  lines.push('# RTL Patch — Layer 4: Translations');
  lines.push(`# Generated by @rtl-first/patch-generator on ${new Date().toISOString().split('T')[0]}`);
  lines.push('# Sets up Arabic locale files');
  lines.push('');
  lines.push('set -e');
  lines.push('');

  if (scanResult.hasArabic) {
    lines.push('echo "✓ Arabic locale already exists"');
    if (scanResult.sourceFile && scanResult.targetFile) {
      lines.push(`echo "  Source: ${scanResult.sourceFile}"`);
      lines.push(`echo "  Target: ${scanResult.targetFile}"`);
    }
  } else if (scanResult.sourceFile) {
    // Determine structure and generate copy commands
    const sourceDir = scanResult.sourceFile;

    if (fs.existsSync(path.join(dir, sourceDir)) && fs.statSync(path.join(dir, sourceDir)).isDirectory()) {
      // Nested dirs
      const targetDir = sourceDir.replace(/en(-US|_US)?$/, lang);
      lines.push(`echo "Creating ${lang} locale from ${sourceDir}..."`);
      lines.push('');
      lines.push(`if [ -d "${targetDir}" ]; then`);
      lines.push(`  echo "⚠ ${targetDir} already exists — skipping"`);
      lines.push('else');
      lines.push(`  cp -r "${sourceDir}" "${targetDir}"`);
      lines.push(`  echo "✓ Created ${targetDir}/ (copy of ${sourceDir}/)"`);
      lines.push(`  echo "  → Now translate the files in ${targetDir}/"`);
      lines.push('fi');
    } else {
      // Flat file
      const targetFile = sourceDir.replace(/en(-US|_US)?\.json$/, `${lang}.json`);
      lines.push(`echo "Creating ${lang} locale from ${sourceDir}..."`);
      lines.push('');
      lines.push(`if [ -f "${targetFile}" ]; then`);
      lines.push(`  echo "⚠ ${targetFile} already exists — skipping"`);
      lines.push('else');
      lines.push(`  cp "${sourceDir}" "${targetFile}"`);
      lines.push(`  echo "✓ Created ${targetFile} (copy of ${sourceDir})"`);
      lines.push(`  echo "  → Now translate ${targetFile}"`);
      lines.push('fi');
    }
  } else {
    lines.push('echo "⚠ No source locale files found"');
    lines.push('echo "  Set up i18n first, then re-run patch generator"');
  }

  return {
    name: '03-locale.sh',
    layer: 4,
    description: 'Set up Arabic locale files',
    content: lines.join('\n'),
    filesAffected: scanResult.hasArabic ? 0 : 1
  };
}

/**
 * Generate the apply-all script
 */
function generateApplyAll(patches, options = {}) {
  const lines = [];
  lines.push('#!/bin/bash');
  lines.push('# RTL Patches — Apply All');
  lines.push(`# Generated by @rtl-first/patch-generator on ${new Date().toISOString().split('T')[0]}`);
  lines.push('# Run this after every upstream rebase');
  lines.push('#');
  lines.push('# Usage:');
  lines.push('#   bash .rtl-patches/apply-all.sh');
  lines.push('#   bash .rtl-patches/apply-all.sh --layer 3   # apply only CSS patch');
  lines.push('');
  lines.push('set -e');
  lines.push('SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"');
  lines.push('');
  lines.push('echo ""');
  lines.push('echo "  RTL Patches — Applying..."');
  lines.push('echo "  ═══════════════════════════"');
  lines.push('echo ""');
  lines.push('');

  // Parse --layer argument
  lines.push('LAYER_FILTER=""');
  lines.push('while [[ $# -gt 0 ]]; do');
  lines.push('  case $1 in');
  lines.push('    --layer) LAYER_FILTER="$2"; shift 2 ;;');
  lines.push('    *) shift ;;');
  lines.push('  esac');
  lines.push('done');
  lines.push('');

  for (const patch of patches) {
    lines.push(`# Layer ${patch.layer}: ${patch.description}`);
    lines.push(`if [ -z "$LAYER_FILTER" ] || [ "$LAYER_FILTER" = "${patch.layer}" ]; then`);
    lines.push(`  echo "  Layer ${patch.layer}: ${patch.description}"`);
    lines.push(`  bash "$SCRIPT_DIR/${patch.name}"`);
    lines.push('  echo ""');
    lines.push('fi');
    lines.push('');
  }

  lines.push('echo "  ═══════════════════════════"');
  lines.push('echo "  Done! Run npx @rtl-first/audit ./ to verify"');
  lines.push('echo ""');

  return {
    name: 'apply-all.sh',
    content: lines.join('\n')
  };
}

/**
 * Generate health check script
 */
function generateHealthCheck() {
  const lines = [];
  lines.push('#!/bin/bash');
  lines.push('# RTL Fork Health Check');
  lines.push(`# Generated by @rtl-first/patch-generator`);
  lines.push('');
  lines.push('echo ""');
  lines.push('echo "  RTL Fork Health Check"');
  lines.push('echo "  ═════════════════════"');
  lines.push('echo ""');
  lines.push('');

  // Commits behind upstream
  lines.push('if git remote | grep -q upstream; then');
  lines.push('  git fetch upstream --quiet 2>/dev/null');
  lines.push('  BEHIND=$(git rev-list HEAD..upstream/main --count 2>/dev/null || echo "?")');
  lines.push('  echo "  Commits behind upstream: $BEHIND"');
  lines.push('else');
  lines.push('  echo "  ⚠ No upstream remote configured"');
  lines.push('  echo "    git remote add upstream <url>"');
  lines.push('fi');
  lines.push('');

  // RTL-specific files vs inline edits
  lines.push('OVERRIDE=$(find rtl-overrides -type f 2>/dev/null | wc -l || echo 0)');
  lines.push('echo "  RTL override files: $OVERRIDE"');
  lines.push('');

  // Patch directory
  lines.push('PATCHES=$(find .rtl-patches -name "*.sh" 2>/dev/null | wc -l || echo 0)');
  lines.push('echo "  Patch scripts: $PATCHES"');
  lines.push('');

  // Last rebase date
  lines.push('if git remote | grep -q upstream; then');
  lines.push('  LAST_MERGE=$(git log --oneline --merges -1 --format="%ar" 2>/dev/null || echo "unknown")');
  lines.push('  echo "  Last merge/rebase: $LAST_MERGE"');
  lines.push('fi');
  lines.push('');
  lines.push('echo ""');

  return {
    name: 'health-check.sh',
    content: lines.join('\n')
  };
}

module.exports = {
  generateDirectionPatch,
  generateCSSPatch,
  generateLocalePatch,
  generateApplyAll,
  generateHealthCheck
};
