/**
 * @rtl-first/patch-generator
 * Generate rebaseable RTL patches organized by layer.
 *
 * Part of the rtl-first framework: https://github.com/imohad/rtl-first
 */

const fs = require('fs');
const path = require('path');
const { readAuditFile, quickScan } = require('./lib/audit-reader');
const { generateDirectionPatch, generateCSSPatch, generateLocalePatch, generateApplyAll, generateHealthCheck } = require('./lib/generators');
const { generateReport, generateJSONReport } = require('./lib/report');

/**
 * Run the patch generator
 * @param {string} dir - Project directory
 * @param {object} options
 * @param {string} options.auditFile - Path to rtl-audit JSON output (optional, will scan if not provided)
 * @param {number[]} options.layers - Which layers to generate patches for (default: [2,3,4])
 * @param {string} options.lang - Target language (default: 'ar')
 * @param {string} options.output - Output directory (default: '.rtl-patches')
 * @param {boolean} options.dryRun - Don't write files
 * @param {boolean} options.json - Return JSON
 */
function run(dir, options = {}) {
  const {
    auditFile = null,
    layers = [2, 3, 4],
    lang = 'ar',
    output = '.rtl-patches',
    dryRun = false,
    json = false
  } = options;

  const absDir = path.resolve(dir);
  const outputDir = path.join(absDir, output);

  if (!fs.existsSync(absDir)) {
    const msg = `Directory not found: ${absDir}`;
    return { success: false, report: json ? { error: msg } : `\n  Error: ${msg}\n` };
  }

  // Step 1: Get scan data (from audit file or quick scan)
  let scanData;
  if (auditFile) {
    scanData = readAuditFile(auditFile);
    if (scanData.error) {
      return { success: false, report: json ? scanData : `\n  Error: ${scanData.error}\n` };
    }
  } else {
    scanData = quickScan(absDir);
    if (scanData.error) {
      return { success: false, report: json ? scanData : `\n  Error: ${scanData.error}\n` };
    }
  }

  // Step 2: Generate patches for selected layers
  const patches = [];

  if (layers.includes(2)) {
    patches.push(generateDirectionPatch(absDir, scanData.layers[2], lang));
  }

  if (layers.includes(3)) {
    patches.push(generateCSSPatch(absDir, scanData.layers[3]));
  }

  if (layers.includes(4)) {
    patches.push(generateLocalePatch(absDir, scanData.layers[4], lang));
  }

  // Step 3: Generate apply-all and health-check
  const applyAll = generateApplyAll(patches);
  const healthCheck = generateHealthCheck();

  // Step 4: Write files
  if (!dryRun) {
    fs.mkdirSync(outputDir, { recursive: true });

    for (const patch of patches) {
      const patchPath = path.join(outputDir, patch.name);
      fs.writeFileSync(patchPath, patch.content, { mode: 0o755 });
    }

    fs.writeFileSync(path.join(outputDir, applyAll.name), applyAll.content, { mode: 0o755 });
    fs.writeFileSync(path.join(outputDir, healthCheck.name), healthCheck.content, { mode: 0o755 });

    // Write a README
    const readme = [
      '# RTL Patches',
      '',
      `Generated by @rtl-first/patch-generator on ${new Date().toISOString().split('T')[0]}`,
      '',
      '## Usage',
      '',
      '```bash',
      '# Apply all patches',
      'bash .rtl-patches/apply-all.sh',
      '',
      '# Apply specific layer',
      'bash .rtl-patches/apply-all.sh --layer 3',
      '',
      '# After upstream rebase',
      'git rebase upstream/main && bash .rtl-patches/apply-all.sh',
      '',
      '# Check fork health',
      'bash .rtl-patches/health-check.sh',
      '```',
      '',
      '## Patches',
      '',
      ...patches.map(p => `- **${p.name}** — Layer ${p.layer}: ${p.description}`),
      '',
      '## Re-generating',
      '',
      'If upstream changes break your patches, re-scan and regenerate:',
      '',
      '```bash',
      `npx @rtl-first/patch-generator ./ --layers ${layers.join(',')}`,
      '```',
      ''
    ].join('\n');

    fs.writeFileSync(path.join(outputDir, 'README.md'), readme);
  }

  // Step 5: Report
  const report = json
    ? generateJSONReport(patches, output)
    : generateReport(patches, output, { dryRun, layers });

  return {
    success: true,
    patches,
    outputDir: output,
    report
  };
}

module.exports = { run, quickScan, readAuditFile };
